image: node:current-alpine

stages:
  - check

client-build:
  stage: check
  script:
    - cd client
    - npm install -g yarn
    - yarn install
    - npm run build

client-format:
  stage: check
  script:
    - cd client
    - npm install -g prettier
    - prettier --check "src/**/*.{ts,tsx,js,jsx}"

server-build:
  stage: check
  script:
    - cd server
    - npm install
    - npm run build

server-format:
  stage: check
  script:
    - cd server
    - npm install -g prettier
    - prettier --check "src/**/*.ts"

server-test:
  stage: check
  script:
    - cd server
    - npm install
    - npm install -g jest
    - jest --env=node --colors --coverage test
