image: node:current-alpine

stages:
  - check

client-build:
  stage: check
  script:
    - cd client
    - yarn install
    - yarn run build

client-format:
  stage: check
  script:
    - cd client
    - yarn global add prettier
    - prettier --check "src/**/*.{ts,tsx,js,jsx}"

server-build:
  stage: check
  script:
    - cd server
    - yarn install
    - yarn run build

server-format:
  stage: check
  script:
    - cd server
    - yarn global add prettier
    - prettier --check "src/**/*.ts"

server-test:
  stage: check
  script:
    - cd server
    - yarn install
    - yarn global add jest
    - jest --env=node --colors --coverage test
